In [1]:
print("hello world")

hello world

# Python Expolaration Data Analysis

- Data Understanding
- Data Cleaning
- Data Visualization
- Data Preprocessing (feature engineering)

In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\PT\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\PT\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PT\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PT\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\PT\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

In [6]:
df=pd.read_csv("cricinfo.csv")

In [7]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [9]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  62 non-null     str
 1   Span    62 non-null     str
 2   Mat     62 non-null     int64
 3   Inns    62 non-null     int64
 4   NO      62 non-null     int64
 5   Runs    62 non-null     int64
 6   HS      62 non-null     str
 7   Ave     62 non-null     float64
 8   BF      62 non-null     str
 9   SR      62 non-null     str
 10  100     62 non-null     int64
 11  50      62 non-null     int64
 12  0       62 non-null     str
 13  4s      62 non-null     int64
 14  6s      62 non-null     int64
dtypes: float64(1), int64(8), str(6)
memory usage: 7.4 KB

In [11]:
df.head() #to view head of data frame

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1

In [12]:
df.tail()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [14]:
df.sample(5)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
29,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530,223,52.29,14372,52.39,24,33,11,957,51
14,SPD Smith (AUS),2010-2025,116,206,25,10271,239,56.74,19176,53.56,36,41,11,1116,61
50,Abid Ali (PAK),2019-2021,16,26,2,1180,215*,49.16,2445,48.26,4,3,2,148,5
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51

In [20]:
df.rename(columns={'Mat':'Matches'},inplace=True)

In [21]:
df.columns

Index(['Player', 'Span', 'Matches', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF',
       'SR', '100', '50', '0', '4s', '6s'],
      dtype='str')

In [23]:
df.rename(columns={'HS': 'Highest_story','Ave': 'Average','BF':'Balls','SR': 'Strike_Rate'},inplace=True)

In [26]:
df.columns

Index(['Player', 'Span', 'Matches', 'Inns', 'NO', 'Runs', 'Highest_story',
       'Average', 'Balls', 'Strike_Rate', '100', '50', '0', '4s', '6s'],
      dtype='str')

In [27]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_story,Average,Balls,Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [32]:
df['country']=df['Player'].str.split(pat="(").str[1]

In [33]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_story,Average,Balls,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS)
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS)
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA)
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS)
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS)
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG)

In [36]:
df['country']=df['country'].str.split(pat=")").str[0]

In [37]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_story  62 non-null     str
 7   Average        62 non-null     float64
 8   Balls          62 non-null     str
 9   Strike_Rate    62 non-null     str
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     str
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(8), object(1), str(6)
memory usage: 7.9+ KB

In [40]:
df['Highest_story']=df['Highest_story'].str.split(pat="*").str[0]

In [42]:
df['Highest_story']=df['Highest_story'].astype(int)

In [43]:
df['Balls']=df['Balls'].str.split(pat="+").str[0]

In [44]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_story,Average,Balls,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [45]:
df.rename(columns={'Balls':'Balls_faced'},inplace=True)

In [48]:
df.rename(columns={'Highest_story':'Highest_score'},inplace=True)

In [49]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [50]:
df[df["0"]=="-"]

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,SL

In [51]:
df[df["Strike_Rate"]=="-"]

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258,2,WI
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107,11,WI
54,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144,48.79,-,-,5,6,3,51,0,ENG

In [52]:
df["Strike_Rate"].replace("-",0)

0      58.6
1     64.38
2     55.68
3     54.48
4        56
      ...
57    49.16
58    59.67
59    44.77
60    60.02
61    25.59
Name: Strike_Rate, Length: 62, dtype: object

In [54]:
df["Balls_faced"].replace("-",0)

0      9800
1      1839
2      2667
3      1707
4       416
      ...
57     8662
58    15525
59     3118
60     3217
61     2110
Name: Balls_faced, Length: 62, dtype: object

In [55]:
df["0"]=df["0"].replace("-",0)

In [56]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110,25.59,1,10,2,53,0,ENG

In [57]:
df.head

<bound method NDFrame.head of                Player       Span  Matches  Inns  NO  Runs  Highest_score  \
0    DG Bradman (AUS)  1928-1948       52    80  10  6996            334
1    PHKD Mendis (SL)  2022-2025       12    21   2  1184            182
2      AC Voges (AUS)  2015-2016       20    31   7  1485            269
3     RG Pollock (SA)  1963-1970       23    41   4  2256            274
4     GA Headley (WI)  1930-1954       22    40   4  2190            270
..                ...        ...      ...   ...  ..   ...            ...
57   KD Walters (AUS)  1965-1981       74   125  14  5357            250
58  GC Smith (ICC/SA)  2002-2014      117   205  13  9265            277
59  WH Ponsford (AUS)  1924-1934       29    48   4  2122            266
60    SJ McCabe (AUS)  1930-1938       39    62   5  2748            232
61   DR Jardine (ENG)  1928-1934       22    33   6  1296            127

    Average Balls_faced Strike_Rate  100  50   0    4s  6s country
0     99.94        9800        58.6   29  13   7   626   6     AUS
1     62.31        1839       64.38    5   4   0   123  23      SL
2     61.87        2667       55.68    5   4   2   186   5     AUS
3     60.97        1707       54.48    7  11   1   246  11      SA
4     60.83         416          56   10   5   2   104   1      WI
..      ...         ...         ...  ...  ..  ..   ...  ..     ...
57    48.26        8662       49.16   15  33   4   525  23     AUS
58    48.25       15525       59.67   27  38  11  1165  24  ICC/SA
59    48.22        3118       44.77    7   6   1   119   0     AUS
60    48.21        3217       60.02    6  13   4   241   5     AUS
61    48.00        2110       25.59    1  10   2    53   0     ENG

[62 rows x 16 columns]>

In [59]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416,56,10,5,2,104,1,WI

In [65]:
df["Balls_faced"] = df["Balls_faced"].str.split(pat="+").str[0]

In [71]:
df["Balls_faced"] = df["Balls_faced"].astype(float)

In [67]:
df["Balls_faced"] = df["Balls_faced"].replace("-", 0)

In [69]:
df["Strike_Rate"] = df["Strike_Rate"].replace("-", 0)

In [70]:
df["Strike_Rate"] = df["Strike_Rate"].astype(float)

In [72]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,53,0,ENG

In [73]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_Rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI