# Python Exploratory Data Analysis
- Data Understanding
- Data Cleaning
- data visualization
- data preprocessing (feature engineering)

In [1]:
#!pip install pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("cricinfo.csv")

In [4]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [5]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='object')

In [6]:
df.info() #information of whole data frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  62 non-null     object
 1   Span    62 non-null     object
 2   Mat     62 non-null     int64
 3   Inns    62 non-null     int64
 4   NO      62 non-null     int64
 5   Runs    62 non-null     int64
 6   HS      62 non-null     object
 7   Ave     62 non-null     float64
 8   BF      62 non-null     object
 9   SR      62 non-null     object
 10  100     62 non-null     int64
 11  50      62 non-null     int64
 12  0       62 non-null     object
 13  4s      62 non-null     int64
 14  6s      62 non-null     int64
dtypes: float64(1), int64(8), object(6)
memory usage: 7.4+ KB

In [7]:
df.head() #to view head of data frame

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1

In [8]:
df.tail()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [9]:
df.sample(5)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
39,ML Hayden (AUS),1994-2009,103,184,14,8625,380,50.73,14349,60.1,30,29,14,1049,82
23,AD Nourse (SA),1935-1951,34,62,7,2960,231,53.81,108+,63.88,9,14,3,115,6
18,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,55.00,178+,29.21,3,6,2,37,2
38,JE Root (ENG),2012-2024,152,278,23,12972,262,50.87,22568,57.47,36,65,13,1394,45
12,KC Sangakkara (SL),2000-2015,134,233,17,12400,319,57.40,22882,54.19,38,52,11,1491,51

In [10]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='object')

In [11]:
df=df.rename(columns={'Mat':'Matches'})

In [12]:
df

,Player,Span,Matches,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [13]:
df.columns

Index(['Player', 'Span', 'Matches', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF',
       'SR', '100', '50', '0', '4s', '6s'],
      dtype='object')

In [14]:
df.rename(columns={'HS':'Highest_score','Ave':'Average','BF':'Balls_faced','SR':'Strike_rate'},inplace=True)

In [15]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [16]:
df['country']=df['Player'].str.split(pat="(").str[1]

In [17]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS)
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS)
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA)
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS)
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS)
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG)

In [18]:
df['country']=df['country'].str.split(pat=")").str[0]

In [19]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     object
 1   Span           62 non-null     object
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     object
 7   Average        62 non-null     float64
 8   Balls_faced    62 non-null     object
 9   Strike_rate    62 non-null     object
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     object
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(8), object(7)
memory usage: 7.9+ KB

In [21]:
df['Highest_score']=df['Highest_score'].str.split(pat="*").str[0]

In [22]:
df['Highest_score']=df['Highest_score'].astype(int)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     object
 1   Span           62 non-null     object
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    62 non-null     object
 9   Strike_rate    62 non-null     object
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     object
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(9), object(6)
memory usage: 7.9+ KB

In [24]:
df

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG

In [25]:
df[df["Strike_rate"]=="-"]

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258,2,WI
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107,11,WI
54,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144,48.79,-,-,5,6,3,51,0,ENG

In [26]:
df["Strike_rate"]=df["Strike_rate"].replace("-",0)

In [27]:
df["Balls_faced"]=df["Balls_faced"].replace("-",0)

In [28]:
df["0"]=df["0"].replace("-",0)

In [29]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,WI

In [30]:
df["Balls_faced"]=df["Balls_faced"].str.split(pat="+").str[0]

In [31]:
df["Balls_faced"]=df["Balls_faced"].astype(float)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     object
 1   Span           62 non-null     object
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    59 non-null     float64
 9   Strike_rate    62 non-null     object
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     object
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(2), int64(9), object(5)
memory usage: 7.9+ KB

In [36]:
df["Strike_rate"]=df["Strike_rate"].astype(float)

In [42]:
df["0"]=df["0"].astype(int)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     object
 1   Span           62 non-null     object
 2   Matches        62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    59 non-null     float64
 9   Strike_rate    62 non-null     float64
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     int64
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(3), int64(10), object(3)
memory usage: 7.9+ KB

In [44]:
df.head()

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI

In [48]:
df["start_year"]=df["Span"].str.split(pat="-").str[0].astype(int)

In [49]:
df["end_year"]=df["Span"].str.split(pat="-").str[1].astype(int)

In [ ]:
df2["Duration"]=df2["end_year"]-df2["start_year"]

In [57]:
df2=df

In [58]:
df1=pd.read_csv("cricinfo.csv")

In [59]:
df1["Span"]

0     1928-1948
1     2022-2025
2     2015-2016
3     1963-1970
4     1930-1954
        ...
57    1965-1981
58    2002-2014
59    1924-1934
60    1930-1938
61    1928-1934
Name: Span, Length: 62, dtype: object

In [61]:
df2["Span"] = df1["Span"]

In [65]:
df2.rename(columns={"span":"Duration(year)"},inplace=True)

In [66]:
df2

,Player,Span,Matches,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country,start_year,end_year,Duration(year)
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS,1928,1948,20
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL,2022,2025,3
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS,2015,2016,1
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA,1963,1970,7
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI,1930,1954,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,525,23,AUS,1965,1981,16
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,1165,24,ICC/SA,2002,2014,12
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,119,0,AUS,1924,1934,10
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,241,5,AUS,1930,1938,8
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,53,0,ENG,1928,1934,6

In [67]:
df.to_csv("cleanedfile.csv")

In [ ]:
df.iloc[]